Fix for SEG-7148, SEG-7149, SEG-7153
* Display status for blobrestored start
* Display nice message if daemon not running if stop is issued
* Verify the command for blobrestore.py driver script and show status

diff --git a/conf/init.d/blobrestored b/conf/init.d/blobrestored
--- a/conf/init.d/blobrestored
+++ b/conf/init.d/blobrestored
@@ -11,6 +11,12 @@ status(){
 start(){
 
     /usr/bin/python26 /opt/membase/membase-backup/blobrestore_utils/blobrestored start > /dev/null 2>&1 &
+    if [ $? -eq 0 ];
+    then
+        echo "Started blobrestore daemon successfully"
+    else
+        echo "Failed to start blobrestore daemon"
+    fi
 }
 
 
